KLEE: input args: /home/jl/deploy/use/build/Release+Asserts/bin/klee --output-dir=/home/jl/testspace/coreutils-bc/cr-3/2019-04-25-00-52-46/klee/klee-out-49 --max-time=120 --max-instruction-time=12 -use --stats-write-interval=238 --istats-write-interval=238 /home/jl/testspace/coreutils-bc/cr-3/2019-04-25-00-52-46/bitcode/symmains.bc_set_fields_ChangeEntry.bc

KLEE: Divergence Instruction: file:/home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c line: 408 test case id is: 1 

KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:419: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: error occurs at the different locations in two versions
old Info: Error: memory error: out of bound pointer
File: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c
Line: 607
assembly.ll line: 1857
Stack: 
	#000001857 in set_fields (fieldstr=31932448) at /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607
	#100012307 in main (=1, =27002288)
Info: 
	address: 31932449
	next: object at 31933536 of size 1
		MO663[1] addr [31933536]:  allocated at set_fields():  %field_found = alloca i8, align 1
	prev: object at 31932448 of size 1
		MO653[1] addr [31932448]:  allocated at main():  %6 = call i8* @malloc(i64 %5)

new Info: Error: memory error: out of bound pointer
File: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c
Line: 607
assembly.ll line: 1857
Stack: 
	#000001857 in set_fields (fieldstr=31932448) at /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607
	#100012307 in main (=1, =27002288)
Info: 
	address: 31932449
	next: object at 31933536 of size 1
		MO663[1] addr [31933536]:  allocated at set_fields():  %field_found = alloca i8, align 1
	prev: object at 31932448 of size 1
		MO653[1] addr [31932448]:  allocated at main():  %6 = call i8* @malloc(i64 %5)

KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:419: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: error occurs at the different locations in two versions
old Info: Error: memory error: out of bound pointer
File: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c
Line: 419
assembly.ll line: 1245
Stack: 
	#000001245 in set_fields (fieldstr=31932448) at /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:419
	#100012307 in main (=1, =27002288)
Info: 
	address: 31932449
	next: object at 31933536 of size 1
		MO663[1] addr [31933536]:  allocated at set_fields():  %field_found = alloca i8, align 1
	prev: object at 31932448 of size 1
		MO653[1] addr [31932448]:  allocated at main():  %6 = call i8* @malloc(i64 %5)

new Info: Error: memory error: out of bound pointer
File: /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c
Line: 607
assembly.ll line: 1857
Stack: 
	#000001857 in set_fields (fieldstr=31932448) at /home/shadowvm/shadow/shadow-test/coreutils/cr-3/src/cut.c:607
	#100012307 in main (=1, =27002288)
Info: 
	address: 31932449
	next: object at 31933536 of size 1
		MO663[1] addr [31933536]:  allocated at set_fields():  %field_found = alloca i8, align 1
	prev: object at 31932448 of size 1
		MO653[1] addr [31932448]:  allocated at main():  %6 = call i8* @malloc(i64 %5)

